### PR TITLE
Add a function to parse a xacro file with arguments

### LINKED ISSUE #60: Add support for passing arguments to xacro files
Currently, there's no way to load a xacro file that expects command line arguments. 

[convert_xacro_to_urdf](https://github.com/openrr/urdf-rs/blob/main/src/utils.rs#L10-L30) expects only a filename, changing the signature is an API breaking change, do you have a better solution or are you ok with breaking the API?

I'm more than happy to implement it!

### PR DESCRIPTION
**Pull request by JafarAbdi**
Fix #60

### CODE REVIEW

**Review by OTL — APPROVED** [review]
Thanks. LGTM!
If there are some tests to confirm this, it will be better.

**Comment by OTL** [comment]
If you want to release this version ASAP, please let me know.

**Comment by JafarAbdi** [comment]
> If you want to release this version ASAP, please let me know.

Yeah, I would really appreciate it. It's needed for https://github.com/openrr/urdf-viz/pull/197

Thanks for the fast review

**Comment by OTL** [comment]
I see. Please wait a moment!

2023年2月13日(月) 18:21 Jafar ***@***.***>:

**Pull request merged**
